# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  # Basic Info
  networking.hostName = "fabian-ghost";
  time.timeZone = "America/Mexico_City";

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80cfa6cd-91db-4e25-ba1c-e1fc70b52532";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6934-3D6E";
      fsType = "vfat";
    };

  boot.initrd.luks.devices.crypted.device = "/dev/disk/by-uuid/f9e6b047-a794-48c4-a39b-1bdffbad218e";
  fileSystems."/home/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0162d5ac-08b5-44d2-ba5a-69edf31fe2de"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
